apiVersion: v2
name: randomsecret
description: An operator materializing RandomSecret resources into Secrets with randomly generated values
type: application
version: 0.1.4
appVersion: 0.1.4
home: https://github.com/nresare/randomsecret
