image:
  repository: public.ecr.aws/portswigger-platform/randomsecret
  # defaults to the chart appVersion
  tag: ""
  pullPolicy: IfNotPresent

# value for the RUST_LOG environment variable
logLevel: info

resources: {}
