image:
  repository: nresare/randomsecret
  # defaults to the chart appVersion
  tag: ""
  pullPolicy: IfNotPresent

# value for the RUST_LOG environment variable
logLevel: info

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}
